import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/LegalPage";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — InventoryFlow" },
      {
        name: "description",
        content:
          "Disclaimer for InventoryFlow, operated by SamVic Technologies. Limitations of liability, accuracy of information, and acceptable use.",
      },
      { property: "og:title", content: "Disclaimer — InventoryFlow" },
      {
        property: "og:description",
        content:
          "Disclaimer for InventoryFlow: accuracy, limitation of liability, third-party services, and acceptable use.",
      },
      { property: "og:url", content: "https://inventoryflowapp.com/disclaimer" },
    ],
    links: [{ rel: "canonical", href: "https://inventoryflowapp.com/disclaimer" }],
  }),
  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      intro={
        <p>
          The information and tools provided by InventoryFlow, operated by SamVic Technologies,
          are intended to assist businesses with operational and inventory management. Use of
          the platform is subject to the disclaimers below.
        </p>
      }
      sections={[
        {
          heading: "General Information",
          body: "InventoryFlow is provided for general business operational use. While we make reasonable efforts to ensure the platform functions as described, no representation or warranty is made regarding completeness, accuracy, reliability, suitability, or availability.",
        },
        {
          heading: "No Professional Advice",
          body: "InventoryFlow does not provide accounting, legal, tax, financial, or regulatory advice. Reports, exports, and operational data generated by the platform are not a substitute for professional review.",
        },
        {
          heading: "Operational Responsibility",
          groups: [
            {
              intro: "Users remain solely responsible for:",
              bullets: [
                "verifying inventory counts and stock movements",
                "validating prices, quantities, and order details",
                "complying with applicable accounting, tax, and regulatory obligations",
                "training authorized users on correct platform usage",
                "maintaining their own backups when business-critical",
              ],
            },
          ],
        },
        {
          heading: "Limitation of Liability",
          groups: [
            {
              intro:
                "To the maximum extent permitted by law, SamVic Technologies shall not be liable for:",
              bullets: [
                "inventory losses or discrepancies",
                "operational decisions based on platform output",
                "accounting or tax discrepancies",
                "loss of profits or business interruption",
                "indirect, incidental, special, consequential, or punitive damages",
                "data loss caused by user error, third-party services, or force majeure events",
              ],
            },
          ],
        },
        {
          heading: "Third-Party Services",
          body: "InventoryFlow integrates with third-party providers (such as hosting, storage, email, and payment processors). SamVic Technologies is not responsible for the performance, availability, or policies of those providers.",
        },
        {
          heading: "Service Availability",
          body: "The platform may experience downtime due to maintenance, updates, or factors outside our control. We do not guarantee uninterrupted, error-free, or fully secure access at all times.",
        },
        {
          heading: "User Accounts",
          body: "Users are responsible for safeguarding their login credentials and for all activity that occurs under their account. Suspicious activity should be reported immediately to support.",
        },
        {
          heading: "Cloud Storage",
          body: "Business data entered into InventoryFlow is stored on cloud infrastructure operated by trusted providers. While reasonable security measures are in place, no online system can guarantee absolute security.",
        },
        {
          heading: "Subscriptions & Payments",
          body: "Future paid subscriptions may be processed through third-party payment providers (such as Stripe). SamVic Technologies is not responsible for issues caused by those providers, including failed charges, currency conversion, or processing delays.",
        },
        {
          heading: "Acceptable Use",
          groups: [
            {
              intro: "Users agree not to:",
              bullets: [
                "use the platform for unlawful purposes",
                "attempt unauthorized access to any part of the system",
                "interfere with platform integrity or performance",
                "upload malicious code or harmful content",
                "resell or redistribute access without authorization",
              ],
            },
          ],
        },
        {
          heading: "Account Termination",
          body: "Accounts may be suspended or terminated for non-payment, misuse, security concerns, or violation of platform policies. Some data may be retained for legal, security, or operational continuity reasons after termination.",
        },
        {
          heading: "External Links",
          body: "InventoryFlow may link to external websites. SamVic Technologies is not responsible for the content, policies, or practices of any third-party site.",
        },
        {
          heading: "Changes to this Disclaimer",
          body: "This Disclaimer may be updated at any time. Continued use of InventoryFlow constitutes acceptance of the latest version.",
        },
        {
          heading: "Contact",
          body: (
            <>
              <p>SamVic Technologies</p>
              <p>
                Website:{" "}
                <a
                  href="https://inventoryflowapp.com"
                  className="text-primary hover:underline"
                  target="_blank"
                  rel="noreferrer"
                >
                  https://inventoryflowapp.com
                </a>
              </p>
            </>
          ),
        },
      ]}
    />
  );
}
