/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupCompleteRouteImport } from './routes/signup-complete'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServiceAgreementRouteImport } from './routes/service-agreement'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as PaymentRequiredRouteImport } from './routes/payment-required'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailConfirmedRouteImport } from './routes/email-confirmed'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransferOrdersRouteImport } from './routes/_authenticated/transfer-orders'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedSalesOrdersRouteImport } from './routes/_authenticated/sales-orders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated/movements'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedLocationStockRouteImport } from './routes/_authenticated/location-stock'
import { Route as AuthenticatedInternalUseRouteImport } from './routes/_authenticated/internal-use'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdjustmentsRouteImport } from './routes/_authenticated/adjustments'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksRunBackupRouteImport } from './routes/api/public/hooks/run-backup'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCompleteRoute = SignupCompleteRouteImport.update({
  id: '/signup-complete',
  path: '/signup-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAgreementRoute = ServiceAgreementRouteImport.update({
  id: '/service-agreement',
  path: '/service-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRequiredRoute = PaymentRequiredRouteImport.update({
  id: '/payment-required',
  path: '/payment-required',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmedRoute = EmailConfirmedRouteImport.update({
  id: '/email-confirmed',
  path: '/email-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferOrdersRoute =
  AuthenticatedTransferOrdersRouteImport.update({
    id: '/transfer-orders',
    path: '/transfer-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesOrdersRoute =
  AuthenticatedSalesOrdersRouteImport.update({
    id: '/sales-orders',
    path: '/sales-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationStockRoute =
  AuthenticatedLocationStockRouteImport.update({
    id: '/location-stock',
    path: '/location-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInternalUseRoute =
  AuthenticatedInternalUseRouteImport.update({
    id: '/internal-use',
    path: '/internal-use',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdjustmentsRoute =
  AuthenticatedAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunBackupRoute = ApiPublicHooksRunBackupRouteImport.update({
  id: '/api/public/hooks/run-backup',
  path: '/api/public/hooks/run-backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/signup': typeof SignupRoute
  '/signup-complete': typeof SignupCompleteRoute
  '/terms': typeof TermsRoute
  '/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/internal-use': typeof AuthenticatedInternalUseRoute
  '/location-stock': typeof AuthenticatedLocationStockRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfer-orders': typeof AuthenticatedTransferOrdersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/signup': typeof SignupRoute
  '/signup-complete': typeof SignupCompleteRoute
  '/terms': typeof TermsRoute
  '/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/internal-use': typeof AuthenticatedInternalUseRoute
  '/location-stock': typeof AuthenticatedLocationStockRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transfer-orders': typeof AuthenticatedTransferOrdersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/checkout': typeof CheckoutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/login': typeof LoginRoute
  '/payment-required': typeof PaymentRequiredRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/signup': typeof SignupRoute
  '/signup-complete': typeof SignupCompleteRoute
  '/terms': typeof TermsRoute
  '/_authenticated/adjustments': typeof AuthenticatedAdjustmentsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/internal-use': typeof AuthenticatedInternalUseRoute
  '/_authenticated/location-stock': typeof AuthenticatedLocationStockRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales-orders': typeof AuthenticatedSalesOrdersRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/transfer-orders': typeof AuthenticatedTransferOrdersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/checkout'
    | '/disclaimer'
    | '/email-confirmed'
    | '/login'
    | '/payment-required'
    | '/pending-approval'
    | '/privacy'
    | '/reset-password'
    | '/service-agreement'
    | '/signup'
    | '/signup-complete'
    | '/terms'
    | '/adjustments'
    | '/admin'
    | '/alerts'
    | '/customers'
    | '/dashboard'
    | '/history'
    | '/internal-use'
    | '/location-stock'
    | '/locations'
    | '/movements'
    | '/permissions'
    | '/products'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/scanner'
    | '/settings'
    | '/setup'
    | '/suppliers'
    | '/transfer-orders'
    | '/users'
    | '/api/public/hooks/run-backup'
    | '/api/public/hooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/checkout'
    | '/disclaimer'
    | '/email-confirmed'
    | '/login'
    | '/payment-required'
    | '/pending-approval'
    | '/privacy'
    | '/reset-password'
    | '/service-agreement'
    | '/signup'
    | '/signup-complete'
    | '/terms'
    | '/adjustments'
    | '/admin'
    | '/alerts'
    | '/customers'
    | '/dashboard'
    | '/history'
    | '/internal-use'
    | '/location-stock'
    | '/locations'
    | '/movements'
    | '/permissions'
    | '/products'
    | '/purchase-orders'
    | '/reports'
    | '/sales-orders'
    | '/scanner'
    | '/settings'
    | '/setup'
    | '/suppliers'
    | '/transfer-orders'
    | '/users'
    | '/api/public/hooks/run-backup'
    | '/api/public/hooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/checkout'
    | '/disclaimer'
    | '/email-confirmed'
    | '/login'
    | '/payment-required'
    | '/pending-approval'
    | '/privacy'
    | '/reset-password'
    | '/service-agreement'
    | '/signup'
    | '/signup-complete'
    | '/terms'
    | '/_authenticated/adjustments'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/internal-use'
    | '/_authenticated/location-stock'
    | '/_authenticated/locations'
    | '/_authenticated/movements'
    | '/_authenticated/permissions'
    | '/_authenticated/products'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/reports'
    | '/_authenticated/sales-orders'
    | '/_authenticated/scanner'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/suppliers'
    | '/_authenticated/transfer-orders'
    | '/_authenticated/users'
    | '/api/public/hooks/run-backup'
    | '/api/public/hooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  CheckoutRoute: typeof CheckoutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EmailConfirmedRoute: typeof EmailConfirmedRoute
  LoginRoute: typeof LoginRoute
  PaymentRequiredRoute: typeof PaymentRequiredRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceAgreementRoute: typeof ServiceAgreementRoute
  SignupRoute: typeof SignupRoute
  SignupCompleteRoute: typeof SignupCompleteRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksRunBackupRoute: typeof ApiPublicHooksRunBackupRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-complete': {
      id: '/signup-complete'
      path: '/signup-complete'
      fullPath: '/signup-complete'
      preLoaderRoute: typeof SignupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-agreement': {
      id: '/service-agreement'
      path: '/service-agreement'
      fullPath: '/service-agreement'
      preLoaderRoute: typeof ServiceAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-required': {
      id: '/payment-required'
      path: '/payment-required'
      fullPath: '/payment-required'
      preLoaderRoute: typeof PaymentRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirmed': {
      id: '/email-confirmed'
      path: '/email-confirmed'
      fullPath: '/email-confirmed'
      preLoaderRoute: typeof EmailConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer-orders': {
      id: '/_authenticated/transfer-orders'
      path: '/transfer-orders'
      fullPath: '/transfer-orders'
      preLoaderRoute: typeof AuthenticatedTransferOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-orders': {
      id: '/_authenticated/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AuthenticatedSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/location-stock': {
      id: '/_authenticated/location-stock'
      path: '/location-stock'
      fullPath: '/location-stock'
      preLoaderRoute: typeof AuthenticatedLocationStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/internal-use': {
      id: '/_authenticated/internal-use'
      path: '/internal-use'
      fullPath: '/internal-use'
      preLoaderRoute: typeof AuthenticatedInternalUseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adjustments': {
      id: '/_authenticated/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AuthenticatedAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-backup': {
      id: '/api/public/hooks/run-backup'
      path: '/api/public/hooks/run-backup'
      fullPath: '/api/public/hooks/run-backup'
      preLoaderRoute: typeof ApiPublicHooksRunBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdjustmentsRoute: typeof AuthenticatedAdjustmentsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInternalUseRoute: typeof AuthenticatedInternalUseRoute
  AuthenticatedLocationStockRoute: typeof AuthenticatedLocationStockRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesOrdersRoute: typeof AuthenticatedSalesOrdersRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTransferOrdersRoute: typeof AuthenticatedTransferOrdersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdjustmentsRoute: AuthenticatedAdjustmentsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInternalUseRoute: AuthenticatedInternalUseRoute,
  AuthenticatedLocationStockRoute: AuthenticatedLocationStockRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesOrdersRoute: AuthenticatedSalesOrdersRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTransferOrdersRoute: AuthenticatedTransferOrdersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  CheckoutRoute: CheckoutRoute,
  DisclaimerRoute: DisclaimerRoute,
  EmailConfirmedRoute: EmailConfirmedRoute,
  LoginRoute: LoginRoute,
  PaymentRequiredRoute: PaymentRequiredRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceAgreementRoute: ServiceAgreementRoute,
  SignupRoute: SignupRoute,
  SignupCompleteRoute: SignupCompleteRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksRunBackupRoute: ApiPublicHooksRunBackupRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
